name: gen_website

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  gen_website:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: merge main -> playground
        uses: devmasx/merge-branch@master
        with:
          github_token: ${{ github.token }}
          type: now
          from_branch: main
          target_branch: playground
      - uses: actions/checkout@v2
        with:
          ref: playground
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - run: pnpm install
      - run: pnpm run build:playground
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: playground
          commit_message: '[Automated] gen website'
